
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculatrice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculatrice
  template:
    metadata:
      labels:
        app: calculatrice
    spec:
      containers:
      - name: calculatrice
        image: mohamedyenge/calculatrice:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: calculatrice-service
spec:
  selector:
    app: calculatrice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
