apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistiques-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistiques
  template:
    metadata:
      labels:
        app: statistiques
    spec:
      containers:
      - name: statistiques
        image: statistiques:dev
        ports:
        - containerPort: 5001