apiVersion: v1
kind: Service
metadata:
  name: statistiques-service
spec:
  selector:
    app: statistiques
  ports:
    - protocol: TCP
      port: 5001       # mÃªme port que le conteneur
      targetPort: 5001 # correspond au Flask app.run(port=5000)
  type: NodePort